# Generated by Django 4.1.7 on 2023-12-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('desc', models.TextField()),
                ('name', models.TextField()),
                ('rating', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
